#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#  Configuration file for "PumpkinVirus".  #
#  @author Nikita Pekin (Indivisible0)     #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#

#======== Virus Settings ==========#

## Regulates the speed at which the virus will spread/duplicate.
# (Note: this is an interval, counted in ticks, between duplications.)
spreadSpeed: 5

## Determines whether or not the virus will attempt to hunt down and kill players by suffocation.
trackingPlayers: false

## Sets the maximum height that virus blocks can be above ground.
# (Note: liquids, air, and the virus itself does not count as ground in this scenario.)
maxHeightOffGround: 3

## The block to be used as the virus
virusBlockType: pumpkin

## The block to be used as the anti-virus
antiVirusBlockType: melon

## Regulates the speed at which the virus will decay.
# Notes:
#   This is an interval, counted in ticks, before the decay is initiated.
#   If set to zero, the blocks will not decay.
virusDecayTime: 0

## Regulates the speed at which the anti-virus will decay.
# Notes:
#   This is an interval, counted in ticks, before the decay is initiated.
#   If set to zero, the blocks will not decay.
antiVirusDecayTime: 5000


#======== Worlds ========#

## List of worlds in which pumpkins are allowed to spread.
worlds:
  - world
  - world_nether