#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
#  Configuration file for "PumpkinVirus".  #
#  @author Nikita Pekin (Indivisible0)     #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#

#======== Virus Settings ==========#

## Regulates the speed at which the virus will spread/duplicate.
# (Note: this is an interval, counted in ticks, between duplications.)
spreadSpeed: 5

## Determines whether or not the virus will attempt to hunt down and kill players by suffocation.
trackingPlayers: false

## Sets the maximum height that virus blocks can be above ground.
# (Note: liquids, air, and the virus itself does not count as ground in this scenario.)
maxHeightOffGround: 3

## Determines whether or not the virus is allowed to spread/duplicate.
spreadEnabled: false

## The block to be used as the virus
virusBlockID: pumpkin
