name: PumpkinVirus
main: in.nikitapek.pumpkinvirus.PumpkinVirusPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin which allows the spread of pumpkins.
dev-url: http://github.com/Indiv0/PumpkinVirus/

commands:
  pumpkinvirus:
    description: Controls the PumpkinVirus plugin.
    aliases: [pv, pumpkin_virus, pumpkinVirus]
    usage: |
      /<command> [world] - Toggles pumpkin spreading (in the current world, unless otherwise specified).