name: PumpkinVirus
main: in.nikitapek.pumpkinvirus.PumpkinVirusPlugin
load: POSTWORLD
version: ${project.version}
author: Indiv0
description: A plugin which allows the spread of pumpkins.
dev-url: http://github.com/Indiv0/PumpkinVirus/

commands:
  pumpkinvirus:
    description: Controls the PumpkinVirus plugin.
    usage: |
      /<command> - Toggles pumpkin spreading.
    aliases: [pv, pumpkin_virus, pumpkinVirus]
    permission: pumpkinvirus.pumpkinvirus
    permission-message: Sorry, you don't have permission to use PumpkinVirus

permissions:
  pumpkinvirus.*:
    description: Controls all PumpkinVirus permissions
    children:
      pumpkinvirus.pumpkinvirus: true
